project:
  type: website

website:
  title: "Dr. Shamiri"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Papers
      - href: blog.qmd
        text: Blog


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

